train: './../train/'
val: './../val/'
test: './../test/'

nc: 130

names: 
  0: shibadog
  1: frenchbulldog
  2: siberianhusky
  3: malamute
  4: pomeranian
  5: ibizanhound
  6: borderterrier
  7: airedale
  8: cairn
  9: miniaturepoodle
  10: irishsetter
  11: affenpinscher
  12: afghanhound
  13: otterhound
  14: staffordshirebullterrier
  15: norwichterrier
  16: lakelandterrier
  17: germanshepherd
  18: leonberg
  19: australianterrier
  20: tibetanterrier
  21: englishsetter
  22: welshspringerspaniel
  23: schipperke
  24: africanhuntingdog
  25: blenheimspaniel
  26: norfolkterrier
  27: curlycoatedretriever
  28: pembroke
  29: tibetanmastiff
  30: newfoundland
  31: filabraziliero
  32: bedlingtonterrier
  33: sussexspaniel
  34: greatdane
  35: irishterrier
  36: scotchterrier
  37: lhasa
  38: irishwolfhound
  39: westhighlandwhiteterrier
  40: briard
  41: brabancongriffo
  42: dhole
  43: bloodhound
  44: redbone
  45: norwegianelkhound
  46: flatcoatedretriever
  47: vizsla
  48: kelpie
  49: bluetick
  50: saluki
  51: dandiedinmont
  52: standardschnauzer
  53: doberman
  54: entlebucher
  55: scottishdeerhound
  56: wirehairedfoxterrier
  57: sealyhamterrier
  58: germanshorthairedpointer
  59: rottweiler
  60: bernesemountaindog
  61: blackandtancoonhound
  62: walkerhound
  63: borzoi
  64: whippet
  65: irishwaterspaniel
  66: kuvasz
  67: saintbernard
  68: mexicanhairless
  69: groenendael
  70: malinois
  71: bouvierdesflandres
  72: greatpyrenees
  73: englishfoxhound
  74: chesapeakebayretriever
  75: brittanyspaniel
  76: bullmastiff
  77: americanstaffordshireterrier
  78: dingo
  79: rhodesianridgeback
  80: silkyterrier
  81: boxer
  82: eskimodog
  83: bostonbull
  84: gordonsetter
  85: greaterswissmountaindog
  86: kerryblueterrier
  87: samoyed
  88: giantschnauzer
  89: softcoatedwheatenterrier
  90: appenzeller
  91: keeshond
  92: chinesecresteddog
  93: collie
  94: toyterrier
  95: weimaraner
  96: clumber
  97: australianshepherd
  98: italiangreyhound
  99: basset
  100: maltesedog
  101: miniatureschnauzer
  102: basenji
  103: blacksable
  104: canecarso
  105: japanesespaniel
  106: japanesespitzes
  107: oldenglishsheepdog
  108: bordercollie
  109: shetlandsheepdog
  110: cockerspaniel
  111: englishspringer
  112: beagle
  113: toypoodle
  114: komondor
  115: cardigan
  116: bichonfrise
  117: standardpoodle
  118: chow
  119: yorkshireterrier
  120: chineseruraldog
  121: labradorretriever
  122: shihtzu
  123: chihuahua
  124: pekinese
  125: goldenretriever
  126: miniaturepinscher
  127: teddy
  128: papillon
  129: pug